In [1]:
import numpy as np
#import numpy

In [2]:
s = np.array([5])
s
#s scalar

array([5])

In [3]:
s.shape

(1,)

In [4]:
v = np.array([1,2,3,4,5])
v
#v vector

array([1, 2, 3, 4, 5])

In [5]:
v.shape

(5,)

In [6]:
#this is how you reshape a vector
v.reshape([5,1])

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [9]:
m = np.array([[1,2,3,4,5],[6,7,8,9,10]])
m
# A matrix

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [10]:
m1 = np.array([[5,6,7],[8,9,10]])
m2 = np.array([[2,3,4],[5,6,7]])
m1 + m2


array([[ 7,  9, 11],
       [13, 15, 17]])

In [11]:
m1.T

array([[ 5,  8],
       [ 6,  9],
       [ 7, 10]])